name: winccua_graphql_client
description: A Flutter GraphQL client library for WinCC Unified servers
version: 1.0.0
homepage: https://github.com/siemens/winccua-graphql-libs

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.1.3
  web_socket_channel: ^2.4.0
  http: ^1.1.0
  rxdart: ^0.27.7
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true